### ISSUE TITLE
Segment cache/node-versions by install-node version

### ISSUE THREAD

**Issue by springmeyer** [mapbox/install-node#24]
We should do this to prevent potential breakage when:

  - A new key is needed to sign a given node version
  - Existing installs of install-node do not know about the keys needed
  - The `cache/node-versions` is bumped to add more versions
  - scripts are using semver to download the latest version

**Comment by yhahn** [comment]
Ok, some quick thinking about this tonight leads to some weird conclusions for me...

- If you pin to a particular version of install-node and its cached node versions list is also version-scoped, then you basically cannot update to newer node versions without updating your reference to install-node.
- Talking through how `install-node` works with @karenzshea I'm wondering if we should not verify node installs at install time but instead at cache/mirror time when we upload to S3.

Will start on this tomorrow first looking at if there's a reason we need to verify at install time. I think the  option I feel best about going forward will be to

- publish our version cache to a new location so the old one stays intact and keeps working for <= install-node@0.2
- verify node builds at cache time and remove gpg verification at install time so that install-node is more resilient to node updates in the future
- still think of segmenting the version cache but not strictly by install-node version and more by (currently unforeseen if we remove gpg verification) install-time breaking changes

cc @rclark @springmeyer @karenzshea

**Comment by springmeyer** [comment]
Sounds good. This is not blocking me, but it would be nice to have for https://github.com/mapbox/mapbox-studio/issues/1209 within the next week or so.

**Comment by karenzshea** [comment]
I'm going to add a `/v.0.0` into the path to `node-version` that corresponds to the major versions of `install_node`

`install_node @ 0.x.x` uses `./cache/0.0.0/node-versions`
`install_node @ 1.x.x` uses `./cache/1.0.0/node-verisons`
etc

**Comment by yhahn** [comment]
@karenzshea sounds good, how would you feel about `./cache/v0` and `./cache/v1` so that no one's confused about the latter 2 digits?

**Comment by karenzshea** [comment]
@springmeyer with https://github.com/mapbox/buildpack/pull/165 v0.12.x of node are supported with buildpack :space_invader:

**Comment by springmeyer** [comment]
Thank you @karenzshea!
